### ISSUE TITLE
INLINE/static inlineの揺らぎ

### ISSUE THREAD

**Issue by jg1uaa** [IchigoJam/ichigojam-firm#6]
z88dkでのビルドを試みた際に気づいたのですが、ichigojam-stddef.hにおいて`#define INLINE static inline`と定義しているにもかかわらず、INLINEを使用せずに`static inline`, `inline static`, `inline`と宣言している関数が大量にあります。

z88dkはinlineに対応しないため、inline宣言は全てINLINEに集約し、コンパイラの違いをichigojam-stddef.hで吸収する必要があります。

（修正箇所があまりにも大量かつ広範囲となるため、先にissueの形で諮ります）

**Comment by taisukef** [comment]
集約、OKです

**Comment by jg1uaa** [comment]
static inlineとただのinlineでは扱いが異なる部分があり、今回の修正によるオブジェクトサイズの変化が懸念されます。
こちらではOpenBSD-7.4/amd64+clangでのビルドしかテストできておりませんので、他環境(SPRSENSE/LPC1114)で問題があった場合は適宜対応を（修正できる方に）お願いします。

**Comment by taisukef** [comment]
static inline は S_INLINE としておきたいですね

**Comment by jg1uaa** [comment]
#7 :修正を撤回し、元々のINLINEが#define static inlineとなっていることから

- INLINE→S_INLINE
- static inline→S_INLINE
- inline→INLINE

という形にまとめ直しました。

**Comment by taisukef** [comment]
ありがとうございます！
