### ISSUE TITLE
basic.h: token_get()

### ISSUE THREAD

**Issue by jg1uaa** [IchigoJam/ichigojam-firm#8]
basic.hの`token_get()`は、戻り値を`struct Token`としています。`Token`の中身は16bitの数値2個だけとはいえ、構造体を戻り値とする関数というのは非効率な気がします。

`static Token token_get()`は`static void token_get(Token *)`として、これに対応するよう各箇所を修正するのが良さそうに思えます。とはいえ修正箇所がかなり多岐にわたり、厄介なバグを仕込む危険性が高そうです。

ざっくり書き換えてOpenBSD-7.4/amd64で試した限りでは、オブジェクトサイズが若干減少しています。他の機種でも有用ならこれを役立ててほしいのですが…問題が無いことを示すための、何か良いテスト方法はないものでしょうか？

**Comment by jg1uaa** [comment]
クロスコンパイラ(arm-linux-gnueabi-gcc)を使用し、ARMv6-M向けのオブジェクトを作成してみました。
最適化なしでは確かにこちらでもオブジェクトサイズが減少するものの、サイズ最適化(-Os)では逆に200byte以上増えてしまう結果を招いています。
元々LPC1114で動かすことを考えて作られている以上、この最適化を行った状態でオブジェクトサイズが増大するような改造は避けたいところですが…Z80向けにz88dkでコンパイルする場合はこの改造が必要になりそうです。PRを投げる前に、こちらで改造したbasic.hを https://github.com/jg1uaa/ichigojam-firm/tree/token/IchigoJam_BASIC に置いておきます。

**Comment by jg1uaa** [comment]
basic.hを、作り直したものに差し替えています。`#define USE_VOID_TOKEN_GET`を定義した場合に`static void token_get(Token *)`で動作し、未定義の場合は旧来と同等の動作となります。

**Comment by taisukef** [comment]
struct Token は、32bitの即値として処理してくれることを期待していました
ARMv6-Mで200byte増はちょっと痛いですね
uint32への代替ではどうでしょうか？

**Comment by jg1uaa** [comment]
色々マージされたので、マージ後のコードをベースにrebaseしました。
ARMv6-M(arm-linux-gnueabi-gcc-12 -march=armv6-m)とx86_64(clang-16)で比較してみたのですが、ｰOsを指定した場合、ARMv6-M/x86_64ともに`#define USE_VOID_TOKEN_GET`を指定した場合にサイズが増えます（指定しない場合は旧来のコードと同一の内容になります）。
- x86_64
```
-rwxr-xr-x  1 uaa  users  42320 Apr 12 20:42 IchigoJam_BASIC*
-rwxr-xr-x  1 uaa  users  41760 Apr 12 20:33 IchigoJam_BASIC.orig*
```
- ARMv6-M
```
-rw-r--r-- 1 uaa uaa 25752  4月 12 21:43 IchigoJam_BASIC
-rw-r--r-- 1 uaa uaa 25648  4月 12 21:43 IchigoJam_BASIC.orig
```
z88dk-sccz80では構造体を戻り値に使用できないため`#define USE_VOID_TOKEN_GET`が必須になるのですが、他にすっきり解決できる手段があるならそちらを使う方が良いと思います。

**Comment by taisukef** [comment]
ありがとうございます
ひとまずコンパイルスイッチでいきましょう
